package server

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/labstack/echo/v4"
)

// testRemoteIP is the address net/http/httptest stamps on synthetic requests.
const testRemoteIP = "192.0.2.1"

// testConfig is the explicit config the tests build on, so they never depend
// on the environment. A test that needs one setting different takes a copy and
// changes that field rather than restating the whole config.
func testConfig() *HttpConfig {
	return &HttpConfig{
		BindAddress:  ":0",
		ReadTimeout:  time.Second,
		WriteTimeout: time.Second,
		MaxBodyLimit: "1M",
		StaticPath:   defaultStaticPath,
		// No origins, which is the shipped default: the suite runs against the
		// CORS posture a deployment that sets nothing actually gets. The tests
		// that need cross-origin access name the origins they need.
		AlllowedOrigins: nil,
		RealIPSource:    RealIPSourcePeer,
	}
}

// newTestServer builds a server on testConfig and returns it with the logger
// it was injected.
func newTestServer(t *testing.T) (*httpServer, *stubLogger) {
	t.Helper()

	return newTestServerWith(t, testConfig())
}

// newTestServerWith builds a server on the given config, failing the test if
// the config is one NewHTTP rejects.
func newTestServerWith(t *testing.T, cfg *HttpConfig) (*httpServer, *stubLogger) {
	t.Helper()

	log := &stubLogger{}

	s, err := NewHTTP(cfg, log)
	if err != nil {
		t.Fatalf("NewHTTP() error = %v, want nil", err)
	}

	return s, log
}

// newHTTPError runs NewHTTP against a config it is expected to reject and
// returns the error. A panic escaping the constructor fails the test on its
// own: middleware.BodyLimit answers a value it cannot parse by panicking, and
// a constructor that returns an error has to report the mistake rather than
// take the process down with it. A nil cfg exercises the env-driven path.
func newHTTPError(t *testing.T, cfg *HttpConfig) error {
	t.Helper()

	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("NewHTTP() panicked with %v, want an error return", r)
		}
	}()

	if _, err := NewHTTP(cfg, &stubLogger{}); err != nil {
		return err
	}

	t.Fatal("NewHTTP() error = nil, want a rejection")
	return nil
}

// do runs a request through the full middleware chain without binding a port.
func do(t *testing.T, s *httpServer, req *http.Request) *httptest.ResponseRecorder {
	t.Helper()

	rec := httptest.NewRecorder()
	s.Echo().ServeHTTP(rec, req)
	return rec
}

// onlyEntry asserts exactly one entry was logged and returns it.
func onlyEntry(t *testing.T, log *stubLogger) logEntry {
	t.Helper()

	entries := log.recorded()
	if len(entries) != 1 {
		t.Fatalf("logged %d entries, want exactly 1: %+v", len(entries), entries)
	}
	return entries[0]
}

// wantField asserts a field was logged with the given value.
func wantField(t *testing.T, e logEntry, key string, want interface{}) {
	t.Helper()

	got, ok := e.field(key)
	if !ok {
		t.Fatalf("field %q missing from log entry: %+v", key, e.fields)
	}
	if got != want {
		t.Errorf("field %q = %#v, want %#v", key, got, want)
	}
}

func TestRequestLoggerEmitsStructuredEntryThroughInjectedLogger(t *testing.T) {
	s, log := newTestServer(t)
	s.Echo().GET("/ping", func(c echo.Context) error {
		return c.String(http.StatusOK, "pong")
	})

	rec := do(t, s, httptest.NewRequest(http.MethodGet, "/ping?verbose=1", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", rec.Code, http.StatusOK)
	}

	entry := onlyEntry(t, log)
	if entry.level != levelInfo {
		t.Errorf("level = %q, want %q", entry.level, levelInfo)
	}
	if entry.msg != requestLogMessage {
		t.Errorf("message = %q, want %q", entry.msg, requestLogMessage)
	}

	wantField(t, entry, "method", http.MethodGet)
	wantField(t, entry, "path", "/ping")
	wantField(t, entry, "uri", "/ping?verbose=1")
	wantField(t, entry, "status", http.StatusOK)
	wantField(t, entry, "remote_ip", testRemoteIP)
	wantField(t, entry, "bytes_out", int64(len("pong")))

	// The request ID generated by the RequestID middleware must reach the log,
	// and must be the same one handed back to the client.
	responseID := rec.Header().Get(echo.HeaderXRequestID)
	if responseID == "" {
		t.Fatal("response is missing the X-Request-ID header")
	}
	wantField(t, entry, "request_id", responseID)

	latency, ok := entry.field("latency")
	if !ok {
		t.Fatal("field \"latency\" missing from log entry")
	}
	if latency == "" {
		t.Error("field \"latency\" is empty")
	}

	if _, ok := entry.field("error"); ok {
		t.Errorf("field \"error\" present on a successful request: %#v", entry.fields)
	}
}

func TestRequestLoggerLogsClientSuppliedRequestID(t *testing.T) {
	s, log := newTestServer(t)
	s.Echo().GET("/ping", func(c echo.Context) error {
		return c.NoContent(http.StatusOK)
	})

	req := httptest.NewRequest(http.MethodGet, "/ping", nil)
	req.Header.Set(echo.HeaderXRequestID, "correlation-id-42")
	do(t, s, req)

	wantField(t, onlyEntry(t, log), "request_id", "correlation-id-42")
}

func TestRequestLoggerSkipsHealthCheckPaths(t *testing.T) {
	tests := []struct {
		name        string
		target      string
		wantEntries int
	}{
		{name: "healthz is skipped", target: healthzPath, wantEntries: 0},
		{name: "versioned healthz is skipped", target: v1HealthzPath, wantEntries: 0},
		{name: "healthz with trailing slash is skipped", target: healthzPath + "/", wantEntries: 0},
		{name: "healthz with query string is skipped", target: healthzPath + "?probe=liveness", wantEntries: 0},
		{name: "normal route is logged", target: "/ping", wantEntries: 1},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s, log := newTestServer(t)
			s.Echo().GET("/ping", func(c echo.Context) error {
				return c.NoContent(http.StatusOK)
			})

			do(t, s, httptest.NewRequest(http.MethodGet, tt.target, nil))

			if got := len(log.recorded()); got != tt.wantEntries {
				t.Errorf("logged %d entries, want %d: %+v", got, tt.wantEntries, log.recorded())
			}
		})
	}
}

func TestHealthCheckEndpointsReturnOK(t *testing.T) {
	for _, path := range []string{healthzPath, v1HealthzPath} {
		t.Run(path, func(t *testing.T) {
			s, _ := newTestServer(t)

			rec := do(t, s, httptest.NewRequest(http.MethodGet, path, nil))

			if rec.Code != http.StatusOK {
				t.Errorf("status = %d, want %d", rec.Code, http.StatusOK)
			}
			if got := rec.Body.String(); got != http.StatusText(http.StatusOK) {
				t.Errorf("body = %q, want %q", got, http.StatusText(http.StatusOK))
			}
		})
	}
}

func TestRequestLoggerLevelBySeverity(t *testing.T) {
	tests := []struct {
		name      string
		handler   echo.HandlerFunc
		wantLevel logLevel
		wantErr   string
	}{
		{
			name:      "success logs at info",
			handler:   func(c echo.Context) error { return c.NoContent(http.StatusOK) },
			wantLevel: levelInfo,
		},
		{
			name:      "client error logs at info",
			handler:   func(c echo.Context) error { return c.NoContent(http.StatusNotFound) },
			wantLevel: levelInfo,
		},
		{
			name:      "server status logs at error",
			handler:   func(c echo.Context) error { return c.NoContent(http.StatusInternalServerError) },
			wantLevel: levelError,
		},
		{
			name:      "returned error logs at error",
			handler:   func(c echo.Context) error { return errors.New("boom") },
			wantLevel: levelError,
			wantErr:   "boom",
		},
		{
			name:      "returned http error logs at error",
			handler:   func(c echo.Context) error { return echo.NewHTTPError(http.StatusBadGateway, "upstream down") },
			wantLevel: levelError,
			wantErr:   "code=502, message=upstream down",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s, log := newTestServer(t)
			s.Echo().GET("/probe", tt.handler)

			do(t, s, httptest.NewRequest(http.MethodGet, "/probe", nil))

			entry := onlyEntry(t, log)
			if entry.level != tt.wantLevel {
				t.Errorf("level = %q, want %q (fields: %#v)", entry.level, tt.wantLevel, entry.fields)
			}

			got, ok := entry.field("error")
			if tt.wantErr == "" {
				if ok {
					t.Errorf("field \"error\" = %#v, want it absent", got)
				}
				return
			}
			if !ok {
				t.Fatalf("field \"error\" missing from log entry: %#v", entry.fields)
			}
			if got != tt.wantErr {
				t.Errorf("field \"error\" = %#v, want %#v", got, tt.wantErr)
			}
		})
	}
}

func TestRequestLoggerLogsStatusSeenByClient(t *testing.T) {
	s, log := newTestServer(t)
	s.Echo().GET("/probe", func(c echo.Context) error {
		return echo.NewHTTPError(http.StatusBadGateway, "upstream down")
	})

	rec := do(t, s, httptest.NewRequest(http.MethodGet, "/probe", nil))
	if rec.Code != http.StatusBadGateway {
		t.Fatalf("status = %d, want %d", rec.Code, http.StatusBadGateway)
	}

	wantField(t, onlyEntry(t, log), "status", http.StatusBadGateway)
}
